### ISSUE TITLE
Pretty-print family names

### ISSUE THREAD

**Issue by mottosso** [pyblish/pyblish-qml#28]
### Goal

![](https://cloud.githubusercontent.com/assets/2152766/5247657/2a122c80-796c-11e4-94f2-5b9273240d61.gif)

When printing family-names, offer an option to use a pretty-printed version of it.

```python
# E.g.
myFamily -> My Family
writeNodes -> Write Nodes
```

However, as family names are useful for debugging, it needs to be an option to the user.

### Implementation

Assume family-names are always `mixedCase`.

```python
# E.g.
assert " " not in family
assert family[0] != family[0].upper()
```

**Comment by mottosso** [comment]
This conflicts with the future [Namespaces](https://github.com/pyblish/pyblish/issues/97). What happens when we pretty-print family names with dots in them?

```yaml
# Option 1
my.family.isCool: my.family.Is Cool

# Option 2
my.family.isCool: My Family Is Cool

# Option 3
my.family.isCool: Is Cool
```

- `option1` is inconsistent
- `option2` shadows which parts are namespaces and which are not.
- `option3` hides which parts are namespaces

Any ideas?
